### ISSUE TITLE
Broken sharing links?

### ISSUE THREAD

**Issue by matheustavares** [pkolaczk/pkolaczk.github.io#1]
Hi @pkolaczk . First of all, awesome blog!

I believe your sharing links (at the bottom of each post page) are broken. They point to the relative URL, not including `"https://pkolaczk.github.io"`. E.g.: https://www.facebook.com/share.php?u=/disk-access-ordering/

**Comment by pkolaczk** [comment]
Thanks for letting me know!


Piotr Kołaczkowski
e. ***@***.***
w. www.datastax.com



czw., 24 cze 2021 o 02:15 Matheus Tavares ***@***.***>
napisał(a):

**Comment by pkolaczk** [comment]
Fixed.
