### ISSUE TITLE
Links in RSS feed.xml pointing to localhost

### ISSUE THREAD

**Issue by sbdchd** [pkolaczk/pkolaczk.github.io#2]
Thanks for the blog!

Some of the links in the feed.xml are pointing to `localhost:4000`

https://github.com/pkolaczk/pkolaczk.github.io/blob/34b2019a48aec91039bd21116a3a3c8be30cb1fb/feed.xml#L1

**Comment by pkolaczk** [comment]
Thank you for reporting. Fixed!
